spring:
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
#        format_sql: true
#    show-sql: true
  sql:
    init:
      mode: always
      platform: postgresql
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}?autoReconnect=true;
    username: ${DB_UNAME:postgres}
    password: ${DB_PASS:1234}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 30
