spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 30
  sql:
    init:
      mode: always
