spring:
  application:
    name: main-library-service
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: testlibrary
        format_sql: ${SHOW_SQL_QUERIES:false}
    show-sql: ${SHOW_SQL_QUERIES:false}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}?autoReconnect=true;
    username: ${DB_UNAME:postgres}
    password: ${DB_PASS:1234}
  sql:
    init:
      platform: postgresql
app:
  checkout:
    default-return-days: 7
  user-session-ttl-seconds: 10800
  new-user-ttl-seconds: 3600
  keep-session-alive-hours: 6
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr([requestId=%X{requestId} sessionId=%X{sessionId}]) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
