spring:
  application:
    name: main-library-service
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: testlibrary
        format_sql: ${SHOW_SQL_QUERIES:false}
    show-sql: ${SHOW_SQL_QUERIES:false}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}?autoReconnect=true;
    username: ${DB_UNAME:postgres}
    password: ${DB_PASS:1234}
  sql:
    init:
      platform: postgresql
app:
  checkout:
    default-return-days: 7
  user-session-ttl-seconds: 10800
  new-user-ttl-seconds: 3600
  keep-session-alive-hours: 6
