spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 30
  sql:
    init:
      mode: always
